name: Build & Test
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_test:
    runs-on: ubuntu-latest
    container:
      image: bdockerimg/bmakelib:0.8.0--opensuse-tumbleweed
    defaults:
      run:
        shell: bash        

    steps:
      - uses: actions/checkout@v4
    
      - name: Install dependencies
        run: >- 
            zypper --non-interactive refresh
            && zypper --non-interactive install java-21-openjdk-devel zip unzip
            && { source /etc/profile || true; }
          
      - name: Install SDKMAN!
        run: >-
          { curl -s "https://get.sdkman.io" | bash; }
          && { source "$HOME/.sdkman/bin/sdkman-init.sh" || true; }
          
      - name: Install SBT
        run: >-
          source $HOME/.sdkman/bin/sdkman-init.sh 
          || true 
          && sdk install sbt

      - name: Run the tests
        run: make test
