name: Build & Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_test:
    runs-on: ubuntu-latest
    container:
      image: bdockerimg/bmakelib:0.8.0--opensuse-tumbleweed

    steps:
      - uses: actions/checkout@v4
    
      - name: Install dependencies
        run: >-
            zypper --non-interactive refresh
              && zypper --non-interactive install java-21-openjdk-devel
              && { source /etc/profile || true; }
              && { curl -s "https://get.sdkman.io" | bash; }
              && source "$HOME/.sdkman/bin/sdkman-init.sh"
              && sdk install sbt

      - name: Run check
        run: make test
