name: Build & Test
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_test:
    runs-on: ubuntu-latest
    container:
      image: bdockerimg/bmakelib:0.8.0--opensuse-tumbleweed
    defaults:
      run:
        shell: bash -l {0}     

    steps:
      - uses: actions/checkout@v4
    
      - name: Install dependencies
        run: >- 
            zypper --non-interactive refresh
            && zypper --non-interactive install java-21-openjdk-devel zip unzip git
            && { source /etc/profile || true; }
            && { curl -s "https://get.sdkman.io" | bash; }
            && { source "$HOME/.sdkman/bin/sdkman-init.sh" || true; }
            && sdk install sbt
          
      - name: Compile
        run: >-
          make compile
          
      - name: Test with coverage report
        run: >-
          make test-with-coverage

      - name: Upload the coverage report
        uses: codecov/codecov-action@v4        
        with:
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}
